### ISSUE TITLE
Search pattern cannot be anywhere in the virtual number

### ISSUE THREAD

**Issue by mirrorps** [2amigos/yii2-nexmo-library#4]
Hi Toni,

Great library 👍 in Yii2 style. 

Is there any way to pass search_pattern as a parameter to Account::searchNumbers as well. Currently the function makes an api call to search numbers that start with the given pattern only (cannot search as a part of the string).

Docs here:
https://docs.nexmo.com/tools/developer-api/number-search#ns_parameters

Thanks.

**Comment by tonydspaniard** [comment]
@mirrorps Thanks... sorry for the big delay. I'll have a look as soon as i have some time. Nevertheless, you are free to make a PR 😉

**Comment by tonydspaniard** [comment]
@mirrorps I have added that parameter on the library. Do you mind checking whether is all OK on "master" branch? If so I'll tag a new version and close this ticket.

**Comment by protexting** [comment]
Hi Tony,

It's OK.

**Comment by mirrorps** [comment]
Hi Tony,

It's OK

**Comment by tonydspaniard** [comment]
@mirrorps Thanks! Tagging version

**Comment by tonydspaniard** [comment]
done!
